name: Update Maven Index

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-maven-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to push changes
    steps:
      - name: Checkout trivy-java-db
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          repository: aquasecurity/trivy-java-db
          ref: 1ac7a8d1246ffc287024b289e05a7a9e85d7f7ae
          path: trivy-java-db

      - name: Checkout maven-index repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          path: maven-index

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b  # v5.4.0
        with:
          go-version-file: trivy-java-db/go.mod

      - name: Build trivy-java-db
        run: |
          cd trivy-java-db
          make build

      - name: Run crawler with Maven Central Index source
        run: |
          cd trivy-java-db
          ./trivy-java-db crawl --index-dir ${GITHUB_WORKSPACE}/maven-index --shards 8192 --source central

      - name: Sort TSV files after Maven Central Index update
        run: |
          cd maven-index
          find . -name "*.tsv" -type f | while read file; do
            echo "Sorting $file"
            # Sort by groupId, artifactId, version (columns 1, 2, 3)
            # Using standard string sort for all columns
            sort -t $'\t' -k1,1 -k2,2 -k3,3 -o "$file" "$file"
          done

      - name: Commit Maven Central Index changes
        run: |
          cd maven-index
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "Update maven index from Maven Central Index" && git push) 
